# Generated by Django 3.2 on 2023-07-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='activation_count',
            field=models.IntegerField(default=0),
        ),
    ]
