# Generated by Django 3.2 on 2023-07-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userlog_activation_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='userlog',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='activation_count',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='last_activation_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
