# Generated by Django 3.2 on 2023-07-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230721_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='activation_count',
        ),
    ]
