# Generated by Django 3.2 on 2023-07-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Light', 'Light'), ('Fan', 'Fan'), ('Plug', 'Plug')], max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
